TryCatchTest6에서 수2에 0을 받으면 div 에러가 나니까

수2를 받을때 0이 들어오면 에러표시 후 수2 재실행